In [2]:
import numpy as np
path = "data_set/datingTestSet.txt"
data = []
labels = []
open_file = open(path,mode='r',encoding='UTF8')
STR = open_file.read()
lines = STR.split('\n')
for line in lines:
    f_l = line.split('\t')
    x1,x2,x3,label = float(f_l[0]),float(f_l[1]),float(f_l[2]),f_l[3]
    data.append([x1,x2,x3])
    labels.append(label)
data = np.array(data)
labels = np.array(labels)

In [3]:
print(data)

[[4.0920000e+04 8.3269760e+00 9.5395200e-01]
 [1.4488000e+04 7.1534690e+00 1.6739040e+00]
 [2.6052000e+04 1.4418710e+00 8.0512400e-01]
 ...
 [2.6575000e+04 1.0650102e+01 8.6662700e-01]
 [4.8111000e+04 9.1345280e+00 7.2804500e-01]
 [4.3757000e+04 7.8826010e+00 1.3324460e+00]]


In [4]:
max_ = np.max(data,axis=0)
min_ = np.min(data,axis=0)
new_data = (data-min_)/(max_-min_)
print(new_data)

[[0.44832535 0.39805139 0.56233353]
 [0.15873259 0.34195467 0.98724416]
 [0.28542943 0.06892523 0.47449629]
 ...
 [0.29115949 0.50910294 0.51079493]
 [0.52711097 0.43665451 0.4290048 ]
 [0.47940793 0.3768091  0.78571804]]


In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(new_data,labels,test_size=0.3,random_state=42)

In [7]:
x_train.shape

(700, 3)

In [8]:
def KNN_model(x_train, x_test, y_train, y_test,K):
    accuracy = 0
    m,n = x_test.shape  
    for i in range(m): 
        data = x_test[i]
        Euclidean_distance = np.power(np.sum((data - x_train)**2,axis=1),0.5)
        sort_k = np.argsort(Euclidean_distance)[:K] 
        get_K_y = y_train[sort_k]
        prob_dict = {}
        for label in get_K_y:
            if label not in prob_dict:
                prob_dict[label] = 1
            else:
                prob_dict[label] += 1
        predict_y = sorted(prob_dict.items(),key=lambda z:z[1],reverse=True)[0][0]
        if predict_y == y_test[i]:
            accuracy += 1
    print('The test set accurate is {}'.format(accuracy / len(y_test)))

In [9]:
KNN_model(x_train,x_test,y_train,y_test,5)

The test set accurate is 0.9233333333333333
